#
#   H A N G M A N
#

import random
import string

print("H A N G M A N")

# List of words, one word will chosen in every game
word_list = ['python', 'java', 'kotlin', 'javascript']
user_input_letter = set()  # for checking user whether user reenterd the same letter or not


def check_input(input):  # for analysing the input
    if len(input) != 1:
        print("You should print a single letter")
        return ""
    if input not in string.ascii_lowercase:
        print("It is not an ASCII lowercase letter")
        return ""
    if input in user_input_letter:
        print("You already typed this letter")
        return ""
    return input


def start_game():  # main events happens here
    word = list(random.choice(word_list))  # one word choosen from word list
    word_len = len(word)
    hint = '-' * len(word)  # word generated by correct input letters
    hint = list(hint)  # converting to list as string is immutable
    user_input_letter.clear()  # we does not want input from last game to interfere
    success = False;
    chance = 8
    while chance != 0:
        print()
        print("".join(hint))  # converting to string
        letter = input("Input a letter: ")
        letter = check_input(letter)  # checking for correctness
        if letter == "":
            continue
        else:
            user_input_letter.add(letter)  # storing user input in hash
        if letter not in word:
            print('No such letter in the word')
            chance -= 1
        else:
            for j in range(word_len):  # embedding correct letter in user's word
                if word[j] == letter:
                    hint[j] = letter
        if hint == word:
            success = True
            break
    if success:
        print()
        print("".join(hint))
        print("You guessed the word!")
        print("You survived!")
        print()
    else:
        print("You are hanged!")
        print()


# Infinite loop
while True:
    exit_game = input('Type "play" to play the game, "exit" to quit: ')
    if exit_game == "exit":
        break
    elif exit_game == "play":
        start_game()
    else:
        print("Unknown choice")
